name: 'pr-comment'
description: 'Adds PR changes'


# Define your inputs here.
inputs:
  owner:
    description: "The owner of the repo"
    required: true
repo:
  description: "the repo name"
  required: true
pr_number:
  description: "the number of the pull request"
  required: true
token:
  description: "token used to access API"
  required: true        

runs:
  using: node20
  main: dist/index.js
